name: Flasktaskr_py3
dependencies:
- click=6.6=py35_0
- flask=0.10.1=py35_2
- flask-wtf=0.11=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- markupsafe=0.23=py35_2
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.11.9=py35_0
- wheel=0.29.0=py35_0
- wtforms=2.0.2=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - flask-sqlalchemy==2.0
  - sqlalchemy==1.0.13

